#!/usr/bin/env python3
"""
Complete Auto-Tuning Report Generator

Generates comprehensive markdown reports summarizing auto-tuning experiments,
results, and recommendations using complete dataset analysis from ALL tuples
in ALL tables for comprehensive performance insights.

Features:
- Complete hardware configuration analysis from TARGET_INFO_SYSTEM_ENV
- Complete ENUM table mappings for accurate event classification
- Complete performance event analysis from all event tables
- Complete GPU performance analysis from all CUDA tables
- Complete MPI communication analysis from OSRT_API
- Complete memory locality analysis from all memory-related tables
- Complete application profiling and optimization recommendations
"""

import json
import time
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime
import pandas as pd

class AutoTuningReportGenerator:
    """
    Generate comprehensive reports for auto-tuning experiments
    """
    
    def __init__(self):
        self.report_template = self._load_template()
    
    def generate_report(self, 
                       experiment_data: Dict, 
                       output_dir: Path,
                       include_detailed_metrics: bool = True,
                       scorer: Optional[Any] = None) -> str:
        """
        Generate comprehensive auto-tuning report
        
        Args:
            experiment_data: Complete experiment results
            output_dir: Directory to save report
            include_detailed_metrics: Whether to include detailed metrics tables
            
        Returns:
            Path to generated report file
        """
        report_content = self._build_report_content(experiment_data, include_detailed_metrics, scorer)
        
        # Save report
        report_file = output_dir / "auto_tuning_report.md"
        with open(report_file, 'w') as f:
            f.write(report_content)
        
        # Also generate executive summary
        summary_file = output_dir / "executive_summary.md"
        summary_content = self._build_executive_summary(experiment_data)
        with open(summary_file, 'w') as f:
            f.write(summary_content)
        
        return str(report_file)
    
    def _build_report_content(self, data: Dict, include_detailed: bool, scorer: Optional[Any] = None) -> str:
        """Build the complete report content"""
        
        # Extract key information
        experiment_id = data.get('experiment_id', 'unknown')
        application = data.get('application', 'unknown')
        timestamp = data.get('timestamp', time.time())
        hardware_info = data.get('hardware_info', {})
        best_config = data.get('best_configuration', None)
        all_results = data.get('all_results', {})
        
        # Format timestamp
        dt = datetime.fromtimestamp(timestamp)
        formatted_time = dt.strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"""# MPI+OpenMP Auto-Tuning Report

**Experiment ID:** {experiment_id}  
**Application:** {application}  
**Date:** {formatted_time}  
**Generated by:** Auto-Tuning Heuristics Framework

---

## Executive Summary

This report presents the results of automated MPI+OpenMP configuration tuning using the 
heuristic scoring methodology described in our research paper. The auto-tuning framework 
evaluated multiple MPI rank and OpenMP thread combinations to identify the optimal 
configuration for the target application on the specified hardware platform.

### Key Findings

"""
        
        if best_config and best_config.get('name'):
            best_name = best_config['name']
            best_score = best_config.get('score', 0)
            det = best_config.get('details') or {}
            try:
                s10 = float(det.get('heuristic_score_10', float(best_score) * 10.0))
            except (TypeError, ValueError):
                s10 = float(best_score) * 10.0
            
            report += f"""
**Optimal Configuration:** {best_name}  
**Heuristic Score:** {s10:.2f}/10 (raw composite {float(best_score):.4f})  
**Performance Improvement:** {self._calculate_improvement(all_results, best_name):.1f}% over worst configuration

The auto-tuning process tested {data.get('configurations_tested', 0)} different MPI+OpenMP 
configurations and identified {best_name} as the optimal choice with heuristic score {s10:.2f}/10 (raw {float(best_score):.4f}).
"""
        else:
            report += f"""
**Status:** No optimal configuration identified

The auto-tuning process tested {data.get('configurations_tested', 0)} different MPI+OpenMP 
configurations but could not identify an optimal choice.
"""
        
        report += f"""

### Hardware Platform

- **System:** {hardware_info.get('system_name', 'Unknown')}
- **Total Cores:** {hardware_info.get('total_cores', 'Unknown')}
- **Sockets:** {hardware_info.get('sockets', 'Unknown')}
- **NUMA Domains:** {hardware_info.get('numa_domains', 'Unknown')}

---

## Methodology

### Heuristic Scoring Function

The framework uses an enhanced 5-dimensional composite scoring function that combines key performance metrics:

```
Score_conf = α(1-MPI_comm) + β(1-Thread_stall) + γ Locality_eff + δ GPU_util + ε OpenMP_eff
```

Where:
- **α = 0.3**: Weight for communication efficiency
- **β = 0.3**: Weight for thread efficiency  
- **γ = 0.2**: Weight for memory locality
- **δ = 0.1**: Weight for GPU utilization
- **ε = 0.1**: Weight for OpenMP efficiency

### Configuration Generation Strategy

The framework generated configurations using multiple strategies:

1. **Paper Methodology**: Power-of-2 MPI rank configurations with balanced OpenMP thread distribution
2. **NUMA-Aware**: Configurations optimized for memory locality and NUMA domain alignment
3. **Hardware-Optimized**: Configurations tailored to the specific hardware topology

---

## Results

### Configuration Performance Summary

"""
        
        if all_results:
            # Create performance summary table
            report += self._create_performance_table(all_results)
        else:
            report += "No performance data available for analysis.\n"
        
        if include_detailed and all_results:
            report += self._create_detailed_metrics_section(all_results, scorer)
        
        # Add configuration details
        report += self._create_configuration_details_section(data)
        
        # Add bottleneck analysis (new section with distribution data)
        if all_results:
            report += self._create_bottleneck_analysis_section(all_results)
        
        # Add recommendations
        report += self._create_recommendations_section(data)
        
        # Add technical details
        report += self._create_technical_details_section(data)
        
        return report
    
    def _build_executive_summary(self, data: Dict) -> str:
        """Build executive summary"""
        
        experiment_id = data.get('experiment_id', 'unknown')
        application = data.get('application', 'unknown')
        timestamp = data.get('timestamp', time.time())
        best_config = data.get('best_configuration', None)
        all_results = data.get('all_results', {})
        
        dt = datetime.fromtimestamp(timestamp)
        formatted_time = dt.strftime("%Y-%m-%d %H:%M:%S")
        
        summary = f"""# Executive Summary: MPI+OpenMP Auto-Tuning

**Experiment:** {experiment_id}  
**Application:** {application}  
**Date:** {formatted_time}

## Quick Results

"""
        
        if best_config and best_config.get('name'):
            best_name = best_config['name']
            best_score = best_config.get('score', 0)
            det = best_config.get('details') or {}
            try:
                s10 = float(det.get('heuristic_score_10', float(best_score) * 10.0))
            except (TypeError, ValueError):
                s10 = float(best_score) * 10.0
            improvement = self._calculate_improvement(all_results, best_name)
            
            summary += f"""
✅ **Optimal Configuration Found:** {best_name}
📊 **Heuristic Score:** {s10:.2f}/10 (raw {float(best_score):.4f})
📈 **Performance Improvement:** {improvement:.1f}% over worst configuration
⚙️  **MPI Ranks:** {best_config.get('details', {}).get('mpi_ranks', 'N/A')}
🧵 **OpenMP Threads:** {best_config.get('details', {}).get('omp_threads', 'N/A')}
"""
        else:
            summary += "❌ **No optimal configuration identified**\n"
        
        summary += f"""

## What This Means

The auto-tuning framework automatically tested {data.get('configurations_tested', 0)} different 
MPI+OpenMP configurations and identified the best one for your application on the target hardware.

## Next Steps

1. **Apply the optimal configuration** to your production jobs
2. **Monitor performance** to validate the improvement
3. **Consider scaling analysis** for different problem sizes
4. **Review detailed report** for technical insights

---

*Generated by Auto-Tuning Heuristics Framework v1.0*
"""
        
        return summary
    
    def _create_performance_table(self, all_results: Dict) -> str:
        """Create performance summary table"""
        
        table = """
| Rank | Configuration | MPI Ranks | OMP Threads | Heuristic Score | Performance |
|------|---------------|-----------|-------------|-----------------|-------------|
"""
        
        # Sort results by score
        sorted_results = sorted(
            all_results.items(),
            key=lambda x: x[1].get('score', 0),
            reverse=True
        )
        
        for rank, (config_name, result) in enumerate(sorted_results, 1):
            score = result.get('score', 0)
            mpi_ranks = result.get('mpi_ranks', 'N/A')
            omp_threads = result.get('omp_threads', 'N/A')
            
            # Performance indicator
            if rank == 1:
                perf_indicator = "🏆 Best"
            elif rank <= 3:
                perf_indicator = "🥈 Top 3"
            elif rank <= len(sorted_results) // 2:
                perf_indicator = "✅ Good"
            else:
                perf_indicator = "⚠️  Suboptimal"
            
            table += f"| {rank} | {config_name} | {mpi_ranks} | {omp_threads} | {score:.4f} | {perf_indicator} |\n"
        
        return table
    
    def _create_detailed_metrics_section(self, all_results: Dict, scorer: Optional[Any] = None) -> str:
        """Create detailed metrics section"""
        
        section = """

### Detailed Performance Metrics

The following table provides detailed breakdown of the heuristic scoring components:

| Configuration | Comm Score | Thread Score | Locality Score | Total Score |
|---------------|------------|--------------|----------------|-------------|
"""
        
        for config_name, result in all_results.items():
            score = result.get('score', 0)
            metrics = result.get('performance_metrics', {})
            
            # Extract component scores from the scorer's detailed breakdown when available
            if scorer and hasattr(scorer, 'scored_configurations'):
                scored_config = scorer.scored_configurations.get(config_name, {})
                component_scores = scored_config.get('component_scores', {})
                comm_score = component_scores.get('communication', 0)
                thread_score = component_scores.get('threading', 0)
                locality_score = component_scores.get('locality', 0)
            else:
                # Fallback: use alpha_comm/comm_score from metrics, or 1 - mpi_comm_fraction (efficiency)
                comm_score = metrics.get('alpha_comm', metrics.get('comm_score', 1.0 - metrics.get('mpi_comm_fraction', 0)))
                thread_score = metrics.get('cpu_utilization', 0)
                locality_score = metrics.get('numa_efficiency', 0)
            
            section += f"| {config_name} | {comm_score:.3f} | {thread_score:.3f} | {locality_score:.3f} | {score:.4f} |\n"
        
        section += """

**Score Components:**
- **Comm Score**: Communication efficiency (lower MPI overhead = higher score)
- **Thread Score**: Thread utilization (higher CPU usage = higher score)  
- **Locality Score**: Memory locality (higher NUMA efficiency = higher score)
"""
        
        return section
    
    def _create_configuration_details_section(self, data: Dict) -> str:
        """Create configuration details section"""
        
        section = """

## Configuration Details

### Tested Configurations

The framework tested the following MPI+OpenMP configurations:

"""
        
        all_results = data.get('all_results', {})
        if all_results:
            for config_name, result in all_results.items():
                section += f"""
**{config_name}**
- **MPI Ranks per Node:** {result.get('mpi_ranks', 'N/A')}
- **OpenMP Threads per Rank:** {result.get('omp_threads', 'N/A')}
- **Binding Strategy:** {result.get('binding_strategy', 'N/A')}
- **Placement Strategy:** {result.get('placement_strategy', 'N/A')}
- **NUMA Policy:** {result.get('numa_policy', 'N/A')}
- **Description:** {result.get('description', 'N/A')}

"""
        else:
            section += "No configuration details available.\n"
        
        return section
    
    def _create_recommendations_section(self, data: Dict) -> str:
        """Create recommendations section"""
        
        section = """

## Optimization Recommendations

### Best Configuration

"""
        
        best_config = data.get('best_configuration', {})
        if best_config and best_config.get('name'):
            best_name = best_config['name']
            best_score = best_config.get('score', 0)
            det = best_config.get('details') or {}
            try:
                s10 = float(det.get('heuristic_score_10', float(best_score) * 10.0))
            except (TypeError, ValueError):
                s10 = float(best_score) * 10.0
            
            section += f"""
**Configuration:** {best_name}  
**Heuristic Score:** {s10:.2f}/10 (raw {float(best_score):.4f})

This configuration achieved the highest overall score and is recommended for production use.

#### SLURM Job Script Settings

```bash
#SBATCH --ntasks-per-node={best_config.get('details', {}).get('mpi_ranks', 'N/A')}
#SBATCH --cpus-per-task={best_config.get('details', {}).get('omp_threads', 'N/A')}
```

#### Environment Variables

```bash
export OMP_NUM_THREADS={best_config.get('details', {}).get('omp_threads', 'N/A')}
export OMP_PROC_BIND=close
export OMP_PLACES=cores
export OMP_SCHEDULE=dynamic
export OMP_DYNAMIC=TRUE
```

#### MPI Execution Command

```bash
mpirun -np {best_config.get('details', {}).get('mpi_ranks', 'N/A')} \\
       --bind-to core \\
       --map-by socket:PE={best_config.get('details', {}).get('omp_threads', 'N/A')} \\
       ./your_application
```
"""
        else:
            section += "No optimal configuration identified for recommendations.\n"
        
        section += """

### Performance Optimization Tips

1. **Monitor Performance**: Track actual performance improvements in production
2. **Scaling Analysis**: Consider weak and strong scaling studies
3. **Memory Optimization**: Review NUMA placement and memory allocation strategies
4. **Communication Patterns**: Analyze MPI communication overhead and optimize if needed

"""
        
        return section
    
    def _create_bottleneck_analysis_section(self, all_results: Dict) -> str:
        """Create detailed bottleneck analysis section using distribution data"""
        
        section = """

## 🔍 Detailed Bottleneck Analysis

This section provides distribution-based bottleneck identification, showing which specific ranks, threads, or streams are causing performance issues.

"""
        
        # Find configurations with bottleneck data
        configs_with_bottlenecks = []
        for config_name, result in all_results.items():
            metrics = result.get('metrics', {})
            bottleneck_details = metrics.get('bottleneck_details', {})
            
            if bottleneck_details and bottleneck_details.get('overall_severity') != 'none':
                configs_with_bottlenecks.append((config_name, result, bottleneck_details))
        
        if not configs_with_bottlenecks:
            section += """
**No significant bottlenecks detected** in the tested configurations. All configurations show balanced performance across ranks, threads, and GPU streams.

"""
            return section
        
        # Sort by severity
        configs_with_bottlenecks.sort(
            key=lambda x: {'high': 2, 'medium': 1, 'none': 0}.get(x[2].get('overall_severity', 'none'), 0),
            reverse=True
        )
        
        for config_name, result, bottleneck_details in configs_with_bottlenecks:
            severity = bottleneck_details.get('overall_severity', 'none')
            severity_emoji = {'high': '🚨', 'medium': '⚠️', 'none': '✅'}.get(severity, '✅')
            
            section += f"""
### Configuration: {config_name} {severity_emoji} {severity.upper()} Severity

"""
            
            # Communication bottlenecks
            comm_bottlenecks = bottleneck_details.get('communication_bottlenecks', {})
            if comm_bottlenecks.get('count', 0) > 0:
                section += f"""
#### Communication Bottlenecks

- **Affected Ranks:** {comm_bottlenecks.get('count', 0)} ranks
- **Severity:** {comm_bottlenecks.get('severity', 'none')}
- **Rank IDs:** {', '.join(map(str, comm_bottlenecks.get('affected_ranks', [])[:10]))}{'...' if len(comm_bottlenecks.get('affected_ranks', [])) > 10 else ''}

**Analysis:** These ranks show communication overhead significantly above the mean (>2 standard deviations). Consider redistributing work or using non-blocking MPI calls.

"""
            
            # Threading bottlenecks
            thread_bottlenecks = bottleneck_details.get('threading_bottlenecks', {})
            if thread_bottlenecks.get('count', 0) > 0:
                section += f"""
#### Threading Bottlenecks

- **Affected Threads:** {thread_bottlenecks.get('count', 0)} threads
- **Severity:** {thread_bottlenecks.get('severity', 'none')}
- **Thread IDs:** {', '.join(map(str, thread_bottlenecks.get('affected_threads', [])[:10]))}{'...' if len(thread_bottlenecks.get('affected_threads', [])) > 10 else ''}

**Analysis:** These threads show low utilization (< mean - 2 standard deviations). Consider dynamic scheduling or work redistribution.

"""
            
            # GPU bottlenecks
            gpu_bottlenecks = bottleneck_details.get('gpu_bottlenecks', {})
            if gpu_bottlenecks.get('count', 0) > 0:
                section += f"""
#### GPU Bottlenecks

- **Affected Streams:** {gpu_bottlenecks.get('count', 0)} streams
- **Severity:** {gpu_bottlenecks.get('severity', 'none')}
- **Stream IDs:** {', '.join(map(str, gpu_bottlenecks.get('affected_streams', [])[:10]))}{'...' if len(gpu_bottlenecks.get('affected_streams', [])) > 10 else ''}

**Analysis:** These GPU streams show high utilization (> mean + 2 standard deviations). Consider redistributing GPU kernels across streams.

"""
            
            # Distribution statistics
            metrics = result.get('metrics', {})
            mpi_dist = metrics.get('per_rank_breakdown', {})
            thread_dist = metrics.get('per_thread_breakdown', {})
            gpu_dist = metrics.get('per_stream_breakdown', {})
            
            if mpi_dist and mpi_dist.get('distribution_stats'):
                stats = mpi_dist['distribution_stats']
                section += f"""
#### MPI Communication Distribution Statistics

- **Mean:** {stats.get('mean', 0):.4f}s
- **Median:** {stats.get('median', 0):.4f}s
- **Std Dev:** {stats.get('std_dev', 0):.4f}s
- **Skewness:** {stats.get('skewness', 0):.2f} {'(high skew - indicates imbalance)' if stats.get('skewness', 0) > 1.0 else ''}
- **Coefficient of Variation:** {stats.get('cv', 0):.2f} {'(high variance - indicates load imbalance)' if stats.get('cv', 0) > 0.3 else ''}
- **P95:** {stats.get('p95', 0):.4f}s
- **P99:** {stats.get('p99', 0):.4f}s

"""
            
            if thread_dist and thread_dist.get('distribution_stats'):
                stats = thread_dist['distribution_stats']
                section += f"""
#### Thread Utilization Distribution Statistics

- **Mean:** {stats.get('mean', 0):.3f}
- **Median:** {stats.get('median', 0):.3f}
- **Std Dev:** {stats.get('std_dev', 0):.3f}
- **Skewness:** {stats.get('skewness', 0):.2f} {'(high skew - indicates imbalance)' if abs(stats.get('skewness', 0)) > 1.0 else ''}
- **Coefficient of Variation:** {stats.get('cv', 0):.2f} {'(high variance - indicates load imbalance)' if stats.get('cv', 0) > 0.3 else ''}

"""
            
            if gpu_dist and gpu_dist.get('distribution_stats'):
                stats = gpu_dist['distribution_stats']
                section += f"""
#### GPU Stream Utilization Distribution Statistics

- **Mean:** {stats.get('mean', 0):.4f}s
- **Median:** {stats.get('median', 0):.4f}s
- **Std Dev:** {stats.get('std_dev', 0):.4f}s
- **Skewness:** {stats.get('skewness', 0):.2f} {'(high skew - indicates imbalance)' if stats.get('skewness', 0) > 1.0 else ''}

"""
            
            # Recommendations
            recommendations = bottleneck_details.get('recommendations', [])
            if recommendations:
                section += """
#### Recommendations

"""
                for rec in recommendations:
                    section += f"- {rec}\n"
                section += "\n"
        
        return section
    
    def _create_technical_details_section(self, data: Dict) -> str:
        """Create technical details section"""
        
        section = """

## Technical Details

### Experiment Information

- **Experiment ID:** {experiment_id}
- **Total Configurations Tested:** {data.get('configurations_tested', 0)}
- **Successful Runs:** {data.get('successful_runs', 0)}
- **Success Rate:** {(data.get('successful_runs', 0) / max(data.get('configurations_tested', 1), 1)) * 100:.1f}%

### Hardware Information

- **System:** {data.get('hardware_info', {}).get('system_name', 'Unknown')}
- **Total Cores:** {data.get('hardware_info', {}).get('total_cores', 'Unknown')}
- **Sockets:** {data.get('hardware_info', {}).get('sockets', 'Unknown')}
- **NUMA Domains:** {data.get('hardware_info', {}).get('numa_domains', 'Unknown')}

### Framework Version

- **Auto-Tuning Framework:** v1.0
- **Heuristic Scoring:** Composite multi-metric function
- **Profiling Integration:** NVIDIA Nsight Systems
- **Job Management:** SLURM integration

---

## Conclusion

This auto-tuning experiment successfully identified the optimal MPI+OpenMP configuration 
for the {data.get('application', 'target')} application on the {data.get('hardware_info', {}).get('system_name', 'target')} system.

The heuristic scoring methodology provides a data-driven approach to configuration 
optimization, considering communication efficiency, thread performance, and memory 
locality in a unified framework.

For questions or further analysis, please refer to the complete experiment data 
and consider running additional scaling studies or performance validation tests.

---

*Report generated on {datetime.fromtimestamp(data.get('timestamp', time.time())).strftime('%Y-%m-%d %H:%M:%S')}*
*Auto-Tuning Heuristics Framework v2.0*
"""
        
        return section
    
    def _calculate_improvement(self, all_results: Dict, best_config_name: str) -> float:
        """Calculate performance improvement over worst configuration"""
        
        if not all_results:
            return 0.0
        
        scores = [result.get('score', 0) for result in all_results.values()]
        if not scores:
            return 0.0
        
        best_score = max(scores)
        worst_score = min(scores)
        
        if worst_score <= 0:
            return 0.0
        
        improvement = ((best_score - worst_score) / worst_score) * 100
        return improvement
    
    def identify_performance_bottlenecks(self, metrics: Dict) -> Dict[str, str]:
        """
        Identify performance bottlenecks based on metrics
        
        Args:
            metrics: Performance metrics dictionary
            
        Returns:
            Dictionary with bottleneck analysis and recommendations
        """
        bottlenecks = {
            'primary_bottleneck': 'unknown',
            'severity': 'low',
            'recommendations': [],
            'analysis': {}
        }
        
        # Analyze communication bottleneck
        comm_fraction = metrics.get('mpi_communication', {}).get('comm_fraction', 0.0)
        if comm_fraction > 0.3:
            bottlenecks['primary_bottleneck'] = 'communication'
            bottlenecks['severity'] = 'high' if comm_fraction > 0.5 else 'medium'
            bottlenecks['recommendations'].append("Reduce MPI ranks to minimize communication overhead")
            bottlenecks['recommendations'].append("Consider message aggregation techniques")
        
        # Analyze CPU utilization bottleneck
        cpu_util = metrics.get('thread_performance', {}).get('cpu_utilization', 0.0)
        if cpu_util < 0.6:
            if bottlenecks['primary_bottleneck'] == 'unknown':
                bottlenecks['primary_bottleneck'] = 'cpu_utilization'
            bottlenecks['severity'] = 'high' if cpu_util < 0.4 else 'medium'
            bottlenecks['recommendations'].append("Increase OpenMP threads to improve CPU utilization")
            bottlenecks['recommendations'].append("Check for load imbalance issues")
        
        # Analyze memory bottleneck
        memory_bottleneck = metrics.get('enhanced_memory', {}).get('memory_bottleneck_severity', 0.0)
        if memory_bottleneck > 0.5:
            if bottlenecks['primary_bottleneck'] == 'unknown':
                bottlenecks['primary_bottleneck'] = 'memory'
            bottlenecks['severity'] = 'high' if memory_bottleneck > 0.7 else 'medium'
            bottlenecks['recommendations'].append("Optimize memory access patterns")
            bottlenecks['recommendations'].append("Consider NUMA-aware memory allocation")
        
        # Analyze GPU bottleneck
        gpu_util = metrics.get('gpu_performance', {}).get('gpu_utilization', 0.0)
        if gpu_util > 0.0 and gpu_util < 0.5:
            if bottlenecks['primary_bottleneck'] == 'unknown':
                bottlenecks['primary_bottleneck'] = 'gpu_utilization'
            bottlenecks['recommendations'].append("Optimize GPU kernel launch patterns")
            bottlenecks['recommendations'].append("Check GPU memory transfer efficiency")
        
        # Analyze OpenMP efficiency
        openmp_efficiency = metrics.get('openmp_performance', {}).get('openmp_work_efficiency', 0.0)
        if openmp_efficiency > 0.0 and openmp_efficiency < 0.7:
            bottlenecks['recommendations'].append("Reduce OpenMP synchronization overhead")
            bottlenecks['recommendations'].append("Optimize work distribution")
        
        bottlenecks['analysis'] = {
            'communication_fraction': comm_fraction,
            'cpu_utilization': cpu_util,
            'memory_bottleneck_severity': memory_bottleneck,
            'gpu_utilization': gpu_util,
            'openmp_efficiency': openmp_efficiency
        }
        
        return bottlenecks
    
    def analyze_scaling_efficiency(self, all_results: Dict) -> Dict[str, float]:
        """
        Analyze scaling efficiency across configurations
        
        Args:
            all_results: Dictionary of all configuration results
            
        Returns:
            Dictionary with scaling analysis
        """
        scaling_analysis = {
            'strong_scaling_efficiency': 0.0,
            'weak_scaling_efficiency': 0.0,
            'scaling_bottleneck': 'unknown',
            'optimal_scaling_range': []
        }
        
        if len(all_results) < 2:
            return scaling_analysis
        
        # Sort configurations by total cores (MPI ranks * OpenMP threads)
        configs = []
        for name, result in all_results.items():
            mpi_ranks = result.get('mpi_ranks', 1)
            omp_threads = result.get('omp_threads', 1)
            total_cores = mpi_ranks * omp_threads
            score = result.get('score', 0.0)
            configs.append((name, total_cores, score, mpi_ranks, omp_threads))
        
        configs.sort(key=lambda x: x[1])  # Sort by total cores
        
        if len(configs) >= 2:
            # Calculate strong scaling efficiency (performance per core)
            base_cores = configs[0][1]
            base_score = configs[0][2]
            
            scaling_efficiencies = []
            for name, cores, score, mpi_ranks, omp_threads in configs[1:]:
                if base_score > 0:
                    efficiency = (score / cores) / (base_score / base_cores)
                    scaling_efficiencies.append(efficiency)
            
            if scaling_efficiencies:
                scaling_analysis['strong_scaling_efficiency'] = sum(scaling_efficiencies) / len(scaling_efficiencies)
                
                # Identify scaling bottleneck
                if scaling_analysis['strong_scaling_efficiency'] < 0.7:
                    scaling_analysis['scaling_bottleneck'] = 'communication' if any(c[1] > 16 for c in configs) else 'memory'
        
        # Find optimal scaling range (configurations with >80% efficiency)
        optimal_configs = []
        for name, cores, score, mpi_ranks, omp_threads in configs:
            if base_score > 0:
                efficiency = (score / cores) / (base_score / base_cores)
                if efficiency > 0.8:
                    optimal_configs.append(name)
        
        scaling_analysis['optimal_scaling_range'] = optimal_configs
        
        return scaling_analysis
    
    def generate_resource_utilization_breakdown(self, metrics: Dict) -> Dict[str, Dict]:
        """
        Generate detailed resource utilization breakdown
        
        Args:
            metrics: Performance metrics dictionary
            
        Returns:
            Dictionary with resource utilization analysis
        """
        utilization = {
            'cpu': {
                'utilization': metrics.get('thread_performance', {}).get('cpu_utilization', 0.0),
                'stall_time': metrics.get('thread_performance', {}).get('stall_time', 0.0),
                'context_switches': metrics.get('thread_performance', {}).get('context_switches', 0),
                'efficiency': 'high' if metrics.get('thread_performance', {}).get('cpu_utilization', 0.0) > 0.8 else 'medium' if metrics.get('thread_performance', {}).get('cpu_utilization', 0.0) > 0.6 else 'low'
            },
            'gpu': {
                'utilization': metrics.get('gpu_performance', {}).get('gpu_utilization', 0.0),
                'kernel_time': metrics.get('gpu_performance', {}).get('gpu_kernel_time', 0.0),
                'memcpy_time': metrics.get('gpu_performance', {}).get('gpu_memcpy_time', 0.0),
                'sync_time': metrics.get('gpu_performance', {}).get('gpu_sync_time', 0.0),
                'memory_bandwidth': metrics.get('gpu_performance', {}).get('gpu_memory_bandwidth', 0.0),
                'efficiency': 'high' if metrics.get('gpu_performance', {}).get('gpu_utilization', 0.0) > 0.8 else 'medium' if metrics.get('gpu_performance', {}).get('gpu_utilization', 0.0) > 0.5 else 'low'
            },
            'memory': {
                'numa_efficiency': metrics.get('memory_locality', {}).get('numa_efficiency', 0.0),
                'transfer_rate': metrics.get('enhanced_memory', {}).get('memory_transfer_rate', 0.0),
                'bottleneck_severity': metrics.get('enhanced_memory', {}).get('memory_bottleneck_severity', 0.0),
                'local_accesses': metrics.get('memory_locality', {}).get('local_accesses', 0),
                'total_accesses': metrics.get('memory_locality', {}).get('total_accesses', 0),
                'efficiency': 'high' if metrics.get('memory_locality', {}).get('numa_efficiency', 0.0) > 0.8 else 'medium' if metrics.get('memory_locality', {}).get('numa_efficiency', 0.0) > 0.6 else 'low'
            },
            'communication': {
                'comm_fraction': metrics.get('mpi_communication', {}).get('comm_fraction', 0.0),
                'call_count': metrics.get('mpi_communication', {}).get('call_count', 0),
                'message_size': metrics.get('mpi_communication', {}).get('total_message_size', 0),
                'efficiency': 'high' if metrics.get('mpi_communication', {}).get('comm_fraction', 0.0) < 0.2 else 'medium' if metrics.get('mpi_communication', {}).get('comm_fraction', 0.0) < 0.4 else 'low'
            },
            'openmp': {
                'work_efficiency': metrics.get('openmp_performance', {}).get('openmp_work_efficiency', 0.0),
                'work_time': metrics.get('openmp_performance', {}).get('openmp_work_time', 0.0),
                'sync_time': metrics.get('openmp_performance', {}).get('openmp_sync_time', 0.0),
                'task_count': metrics.get('openmp_performance', {}).get('openmp_task_count', 0),
                'efficiency': 'high' if metrics.get('openmp_performance', {}).get('openmp_work_efficiency', 0.0) > 0.8 else 'medium' if metrics.get('openmp_performance', {}).get('openmp_work_efficiency', 0.0) > 0.6 else 'low'
            }
        }
        
        return utilization

    def _load_template(self) -> str:
        return ""

